language: python
python:
  - "2.7"
script:
  - python calculator.py
  - python calculator_tests.py
after_success:
  - pip install coverage
  - coverage run calculator.py
  - touch report.txt
  - coverage report > report.txt
  - git add report.txt
  - git commit -m "Coverage"
  - git push origin HEAD:github